- name: Add Users to sudoer file
  blockinfile:
    path: /etc/sudoers
    block: |
      %redmine ALL=(ALL:ALL) NOPASSWD: /usr/bin/apt-get,/usr/bin/apt-key,/usr/bin/apt-get install,/usr/bin/apt update,/usr/bin/apt install -y
      {% for item in user_list | json_query("[*].name") %}
      %{{ item }} ALL=(ALL:ALL) NOPASSWD: /usr/bin/apt-get,/usr/bin/apt-key,/usr/bin/apt-get install,/usr/bin/apt update,/usr/bin/apt install -y
      {% endfor %}
    state: present
    validate: "/usr/sbin/visudo -cf %s"
  register: sudoers_status

- name: A Block of tasks
  block:
    - name: RVM GPG key
      command: "gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys {{ item }}"
      loop: "{{ rvm_keyids }}"

    - name: Installing RVM on User {{ user_item }}
      shell: "curl -sSL https://get.rvm.io | bash -s stable"

    - name: "Add RVM environment variable to user {{ user_item }}"
      blockinfile:
        path: "~/.bashrc"
        block: |
          if [ -f $HOME/.rvm/scripts/rvm ]; then
            source $HOME/.rvm/scripts/rvm
          fi
          rvm use {{ ruby_version }} --default

    - name: "Installing Ruby-{{ ruby_version }} on user {{ user_item }}"
      shell: "{{ item }}"
      environment:
        PATH: "{{ RVM_ENVIRONMENT }}:{{ ansible_env.PATH }}"
      loop: "{{ install_process }}"
  become_user: "{{ user_item }}"

- name: Delete User to sudoer file
  blockinfile:
    path: /etc/sudoers
    state: absent
    validate: "/usr/sbin/visudo -cf %s"
