rvm_keyids: 
  - 409B6B1796C275462A1703113804BB82D39DC0E3
  - 7D2BAF1CF37B13E2069D6956105BD0E739499BDB

ruby_version: "3.0"
mariadb_version: "10.6"
php_version: "7.4"
es_version: "7.4.0"
php_date_time: "Asia/Tokyo"

RUBY_ENVIRONMENT: "/home/{{ user_item }}/.rvm/rubies/ruby-{{ ruby_version }}/bin"
RVM_ENVIRONMENT: "/home/{{ user_item }}/.rvm/bin"

install_process:
  - "rvm install {{ ruby_version }}"
  - "rvm use {{ ruby_version }} --default"

sys_packages:
  - nginx
  - postgresql 
  - postgresql-contrib

apt_docker_repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ lsb_release.stdout }} stable"
apt_mariadb_repo: "deb [arch=amd64,arm64,ppc64el] http://sfo1.mirrors.digitalocean.com/mariadb/repo/{{ mariadb_version }}/ubuntu {{ lsb_release.stdout }} main"
apt_elastic_deb: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}-amd64.deb"
apt_docker_dependencies:
  - ca-certificates
  - curl
  - gnupg
  - lsb-release

docker_packages:
  - docker-ce 
  - docker-ce-cli 
  - containerd.io

php_packages:
  - "php{{ php_version }}"
  - "php{{ php_version }}-fpm"

build_essential_packages: 
  - net-tools 
  - autoconf 
  - libfcgi-dev 
  - libfcgi0ldbl 
  - libjpeg-turbo8-dev 
  - libmcrypt-dev 
  - libssl-dev 
  - libc-client2007e 
  - libc-client2007e-dev 
  - libxml2-dev 
  - libbz2-dev 
  - libcurl4-openssl-dev 
  - libjpeg-dev 
  - libpng-dev 
  - libfreetype6-dev 
  - libkrb5-dev 
  - libpq-dev 
  - libxml2-dev 
  - libxslt1-dev 
  - libzip-dev 
  - libsqlite3-dev 
  - libonig-dev 
  - build-essential

php_options: "--with-pdo-pgsql --with-zlib-dir --with-freetype --enable-mbstring --enable-soap --enable-calendar --with-curl --with-zlib --enable-gd --with-pgsql --disable-rpath --enable-inline-optimization --with-bz2 --with-zlib --enable-sockets --enable-sysvsem --enable-sysvshm --enable-pcntl --enable-mbregex --enable-exif --enable-bcmath --with-mhash --with-zip --with-pdo-mysql --with-mysqli --with-mysql-sock=/var/run/mysqld/mysqld.sock --with-jpeg --with-openssl --with-fpm-user=www-data --with-fpm-group=www-data --with-libdir=/lib/x86_64-linux-gnu --enable-ftp --with-imap --with-imap-ssl --with-kerberos --with-gettext --with-xmlrpc --with-xsl --enable-opcache --enable-intl --with-pear --enable-fpm"
url_php_tarball: "https://www.php.net/distributions/php-{{ php_version }}.tar.gz"
php_tarfile: "{{ url_php_tarball | basename }}"
php_prefix: "/opt/php-{{ php_version }}"
php_configs:
  - { src: "/tmp/{{ php_tarfile }}/etc/php-fpm.d/www.conf.default", dest: "{{ php_prefix }}/etc/php-fpm.d/www.conf" }
  - { src: "/tmp/{{ php_tarfile }}/etc/php-fpm.conf.default", dest: "{{ php_prefix }}/etc/php-fpm.conf" }
  - { src: "/tmp/{{ php_tarfile }}/php.ini-production", dest: "{{ php_prefix }}/lib/php.ini" }

mariadb_key: "https://mariadb.org/mariadb_release_signing_key.asc"
yum_docker_repo: "https://download.docker.com/linux/centos/docker-ce.repo"
yum_mariadb_repo: "http://yum.mariadb.org/{{ mariadb_version }}/centos7-amd64"
yum_mariadb_key: "https://yum.mariadb.org/RPM-GPG-KEY-MariaDB"
yum_elasticsearch_rpm: "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ es_version }}-x86_64.rpm"